// <auto-generated />
using IB_Timetabler.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IB_Timetabler.Migrations
{
    [DbContext(typeof(IBTimetablerContext))]
    [Migration("20211117215705_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("IB_Timetabler.Models.Block", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<long>("Block1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Block");

                    b.HasKey("Id");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("IB_Timetabler.Models.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("NumLessons")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TeacherId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TeacherID");

                    b.Property<long>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("IB_Timetabler.Models.LessonIdblockId", b =>
                {
                    b.Property<long>("BlockId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BlockID");

                    b.Property<long>("LessonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LessonID");

                    b.ToTable("LessonIDBlockID");
                });

            modelBuilder.Entity("IB_Timetabler.Models.Period", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<long>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimePeriod")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("IB_Timetabler.Models.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<long>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("IB_Timetabler.Models.RoomIdlessonId", b =>
                {
                    b.Property<long>("LessonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LessonID");

                    b.Property<long>("RoomId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoomID");

                    b.ToTable("RoomIDLessonID");
                });

            modelBuilder.Entity("IB_Timetabler.Models.Save", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Saves");
                });

            modelBuilder.Entity("IB_Timetabler.Models.SavedLesson", b =>
                {
                    b.Property<string>("Lesson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SaveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SaveID");

                    b.Property<string>("Teacher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("SavedLessons");
                });

            modelBuilder.Entity("IB_Timetabler.Models.SavedLessonIdperiodId", b =>
                {
                    b.Property<long>("PeriodId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PeriodID");

                    b.Property<long>("SavedLessonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SavedLessonID");

                    b.ToTable("SavedLessonIDPeriodID");
                });

            modelBuilder.Entity("IB_Timetabler.Models.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
